version: '3'
services:
  web:
    build: ../
    ports:
     - "5000:5000"
    links:
     - db
    volumes:
     - ../src:/opt/src
  redis:
    image: "redis:3.0.7"
  db:
    build: ../mysql/
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../mysql:/docker-entrypoint-initdb.d/:ro
    command: --default-authentication-plugin=mysql_native_password